
import React, { useState, useEffect, useMemo } from 'react';
import type { Component, Document, AMP, FactorDefinition } from '../types';
import { mockDocuments, mockAmps, mockFleets, mockFactorDefinitions } from '../data/mockDatabase';
import { XMarkIcon, CheckCircleIcon, DocsIcon, TagIcon, BookOpenIcon, AdjustmentsHorizontalIcon } from './Icons';
import { SearchableSelector } from './SearchableSelector';

interface ComponentEditModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSave: (component: Component) => void;
    component: Component | null;
}

const emptyComponent: Omit<Component, 'lastModifiedBy' | 'lastModifiedDate'> = {
    id: '',
    partNumber: '',
    description: '',
    sourceDocumentIds: [],
    ampIds: [],
    allowedFactorIds: [],
    status: 'Active',
    notes: '',
};

export const ComponentEditModal: React.FC<ComponentEditModalProps> = ({ isOpen, onClose, onSave, component }) => {
    const [data, setData] = useState<Omit<Component, 'lastModifiedBy' | 'lastModifiedDate'>>(emptyComponent);
    
    useEffect(() => {
        if (isOpen) {
            const initial = component || emptyComponent;
            setData({
                ...initial,
                ampIds: initial.ampIds || [],
                allowedFactorIds: initial.allowedFactorIds || [],
            });
        }
    }, [component, isOpen]);

    const handleFieldChange = (field: keyof Component, value: any) => {
        setData(prev => ({ ...prev, [field]: value }));
    };

    const allActiveFactors = useMemo(() => {
        return mockFactorDefinitions.filter(f => f.status === 'Active');
    }, []);

    const handleAllowedFactorToggle = (factorId: string) => {
        const currentFactors = data.allowedFactorIds || [];
        const newFactors = currentFactors.includes(factorId)
            ? currentFactors.filter(id => id !== factorId)
            : [...currentFactors, factorId];
        setData(prev => ({ ...prev, allowedFactorIds: newFactors }));
    };

    const renderDocumentItem = (doc: Document) => (
        <div className="flex-1 flex justify-between items-center text-sm">
            <div className="truncate">
                <p className="font-medium text-white truncate max-w-[300px]">{doc.title}</p>
                <p className="text-xs text-gray-400">{doc.docType} - Rev {doc.revision}</p>
            </div>
            <span className="text-xs font-mono text-gray-500 ml-2">{doc.id}</span>
        </div>
    );

    const renderAmpItem = (amp: AMP) => (
        <div className="flex-1 flex justify-between items-center text-sm">
            <div className="truncate">
                <p className="font-medium text-white">{amp.name}</p>
                <p className="text-xs text-gray-400">{mockFleets.find(f => f.id === amp.fleetId)?.name || 'Sin Flota'}</p>
            </div>
            <span className="text-xs font-mono text-gray-500 ml-2">Rev. {amp.revision}</span>
        </div>
    );

    const handleSubmit = () => {
        if (!data.id && component) {
             // Edit mode check
        }
        // In Add mode, ID is generated by DB.
        // P/N is the main identifier for the user.
        if (!data.partNumber || !data.description) {
            alert("P/N y Descripción son obligatorios.");
            return;
        }
        onSave(data as Component);
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-sm flex items-center justify-center z-50 p-4">
            <div className="bg-gray-800 border border-gray-700 rounded-xl shadow-2xl w-full max-w-6xl h-[95vh] flex flex-col">
                <header className="flex justify-between items-center p-4 border-b border-gray-700 flex-shrink-0">
                    <h2 className="text-xl font-bold text-white">
                        {component ? 'Editar Componente' : 'Nuevo Componente'}
                    </h2>
                    <button onClick={onClose} className="text-gray-400 hover:text-white"><XMarkIcon className="h-6 w-6" /></button>
                </header>

                <main className="p-6 flex-1 min-h-0 overflow-y-auto">
                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                        {/* Columna 1: Datos Básicos */}
                        <div className="lg:col-span-1 space-y-4">
                            <div className="bg-gray-900/30 p-4 rounded-lg border border-gray-700 space-y-4">
                                <h3 className="text-lg font-semibold text-sky-400 border-b border-gray-600 pb-2 flex items-center gap-2"><TagIcon className="h-5 w-5"/> Identificación</h3>
                                
                                <div>
                                    <label className="block text-sm font-medium text-gray-300">P/N (Part Number)</label>
                                    <input type="text" value={data.partNumber} onChange={e => handleFieldChange('partNumber', e.target.value)} className="mt-1 block w-full rounded-md bg-gray-700 text-white font-mono" placeholder="Ej: 350A11-0010-00" />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-300">Descripción</label>
                                    <input type="text" value={data.description} onChange={e => handleFieldChange('description', e.target.value)} className="mt-1 block w-full rounded-md bg-gray-700 text-white" />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-300">Estado</label>
                                    <select value={data.status} onChange={e => handleFieldChange('status', e.target.value)} className="mt-1 block w-full rounded-md bg-gray-700 text-white border-transparent focus:border-sky-500 focus:ring-sky-500">
                                        <option value="Active">Activo</option>
                                        <option value="Inactive">Inactiva</option>
                                    </select>
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-300">Notas</label>
                                    <textarea rows={3} value={data.notes} onChange={e => handleFieldChange('notes', e.target.value)} className="mt-1 block w-full rounded-md bg-gray-700 text-white" />
                                </div>
                            </div>

                            {/* Factores Soportados */}
                            <div className="bg-gray-900/30 p-4 rounded-lg border border-gray-700 flex flex-col">
                                <h3 className="text-lg font-semibold text-sky-400 mb-2 flex items-center gap-2">
                                    <AdjustmentsHorizontalIcon className="h-5 w-5"/> Factores (Ingeniería)
                                </h3>
                                <p className="text-xs text-gray-400 mb-4">¿Qué parámetros físicos afectan a esta pieza?</p>
                                
                                <div className="flex-1 overflow-y-auto pr-2 grid grid-cols-1 gap-2 content-start">
                                    {allActiveFactors.map(factor => (
                                        <label key={factor.id} className={`flex items-center space-x-3 p-2 rounded cursor-pointer transition border ${data.allowedFactorIds.includes(factor.id) ? 'bg-sky-900/20 border-sky-500' : 'bg-gray-800 border-gray-700 hover:bg-gray-700'}`}>
                                            <input 
                                                type="checkbox" 
                                                checked={data.allowedFactorIds?.includes(factor.id)} 
                                                onChange={() => handleAllowedFactorToggle(factor.id)}
                                                className="h-4 w-4 rounded border-gray-500 bg-gray-600 text-sky-500 focus:ring-sky-600"
                                            />
                                            <div className="flex-1 flex justify-between items-center">
                                                <span className={`text-sm ${data.allowedFactorIds.includes(factor.id) ? 'text-white' : 'text-gray-300'}`}>{factor.name}</span>
                                                <span className="text-xs text-gray-500 font-mono">{factor.id}</span>
                                            </div>
                                        </label>
                                    ))}
                                </div>
                            </div>
                        </div>

                        {/* Columna 2 & 3: Asociaciones */}
                        <div className="lg:col-span-2 space-y-4 flex flex-col h-full">
                            <div className="flex-1 min-h-0 bg-gray-900/50 p-4 rounded-lg border border-gray-700 flex flex-col">
                                <h3 className="text-lg font-semibold text-white mb-2 flex items-center gap-2"><BookOpenIcon className="h-5 w-5 text-sky-400"/> AMPs Asociados</h3>
                                <p className="text-xs text-gray-400 mb-2">Define en qué programas de mantenimiento es válido este componente.</p>
                                <div className="flex-grow min-h-0">
                                    <SearchableSelector 
                                        items={mockAmps.filter(c => c.status === 'Active')}
                                        selectedIds={data.ampIds || []} 
                                        onSelectionChange={(ids) => handleFieldChange('ampIds', ids)}
                                        renderItem={renderAmpItem}
                                        placeholder="Buscar AMPs..."
                                        maxSelections={100}
                                        itemIdentifier="id"
                                    />
                                </div>
                            </div>

                            <div className="flex-1 min-h-0 bg-gray-900/50 p-4 rounded-lg border border-gray-700 flex flex-col">
                                <h3 className="text-lg font-semibold text-white mb-2 flex items-center gap-2"><DocsIcon className="h-5 w-5 text-sky-400"/> Documentación Base</h3>
                                <div className="flex-grow min-h-0">
                                    <SearchableSelector 
                                        items={mockDocuments.filter(d => d.status === 'Active')}
                                        selectedIds={data.sourceDocumentIds}
                                        onSelectionChange={(ids) => handleFieldChange('sourceDocumentIds', ids)}
                                        renderItem={renderDocumentItem}
                                        placeholder="Buscar documentos..."
                                        maxSelections={100}
                                        itemIdentifier="id"
                                    />
                                </div>
                            </div>
                        </div>
                    </div>
                </main>

                <footer className="flex justify-end items-center p-4 border-t border-gray-700 flex-shrink-0 gap-3">
                    <button onClick={onClose} className="bg-gray-600 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded-lg shadow-md transition-colors">Cancelar</button>
                    <button onClick={handleSubmit} className="bg-sky-500 hover:bg-sky-600 text-white font-bold py-2 px-4 rounded-lg shadow-md transition-colors flex items-center gap-2"><CheckCircleIcon className="h-5 w-5"/> Guardar Componente</button>
                </footer>
            </div>
        </div>
    );
};
